LIBNAME cv "C:\Users\virendsi\Google Drive\Projects\Copart\CopartData";run;
proc import datafile = 'path\CD.csv'
out = cv.file_1
dbms=csv  
replace;
getname=yes;
run;


proc print data =cv.file_1(obs=10);run;

/* cleaning dataset for yard positioning*/

data cv.yard(keep=HEAVY_TOW_YORN
YARD_ROW_LOCATION
YARD_NUMBER
YARD_NAME
YARD_CITY
YARD_COUNTY
YARD_STATE
YARD_COUNTRY
YARD_ZIP
PU_LOCATION_CITY
PU_LOCATION_STATE
PU_LOCATION_ZIP
PU_LOCATION_COUNTRY
PU_LOCATION_COUNTY
PU_LOCATION_AREA_CODE
TOW_COST
ADVANCE_CHARGES_TOWING
ADVANCE_CHARGES_STORAGE
ADVANCE_CHARGES_LABOR
ADVANCE_CHARGES_YARDORGATE
ADVANCE_CHARGES_ESTIMATE
ADVANCE_CHARGES_MISCELLANOUS
ADVANCE_CHARGES_TAXES
ADVANCE_CHARGES_CREDITS
TOTAL_ADVANCE_CHARGES
TOTAL_CHARGE_AMOUNT
);
set cv.file_1;
run;
/* data for demo regression*/ 
data cv.regress(
keep =BEST_HIGH_BID
BIDDERS_COUNT
BID_COUNT
AUCTION_CALENDAR_DAYS
AUCTION_DATE
BUYER_FINAL_PAY_DATE
BUYER_NUMBER
BUYER_PAID_CALENDAR_DAYS
BUYER_STATE
CHARGES_CLEARED_DATE
HIGH_BID
KEYS_YORN
LICENSE_PLATE_STATE
LOSS_TYPE
LOT_MAKE
LOT_MODEL
LOT_NUMBER
LOT_STAGE
LOT_YEAR
MINIMUM_BID
LOT_BODY_STYLE
LOT_COLOR
ODOMETER_READING
ORIGINAL_TITLE_DATE
ORIG_TITLE_DESCRIPTION
ORIG_TITLE_GROUP
ORIG_TITLE_STATE
ORIG_TITLE_TYPE
PAID_ADVANCE_CHARGES
PAID_COPART_CHARGES
PAYMENT_AMOUNT
PROQUOTE_AMOUNT
PURCHASE_AMOUNT
REPAIR_COST
SALVAGE_TYPE
SELLER_CITY
SELLER_REGION
SELLER_STATE
);
set cv.file_1;
run;

proc print data =cv.yard(obs=10);run;

proc sgplot data=cv.yard;
scatter x= YARD_STATE y= TOW_COST;
run;


proc sgplot data=cv.regress;
scatter x= SELLER_STATE y= BID_COUNT;
run;
